functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - У пользователя должна быть возможность использовать разные языки программирования
  - Пользователь должен иметь возможность создавать игру
  - Пользователь должен иметь возможность выбрать уровень сложности игры
  - Пользователь должен иметь возможность выбора задания для игры
  - Пользователь должен иметь возможность выбрать игру с ботом
  - Пользователь должен иметь возможность играть с другом по ссылке
  - Пользователь должен регулировать временной интервал в котором будет длиться игра
  - На сайте должна быть возможность проведения турнирова
  - На сайте должна быть реализованна система рейтинга
  - На сайте должен быть реализован чат между игроками находящимися в лобби
  - На сайте должна быть реализованна функиця истории игр
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Предоставить пользователю возможно поменять аватар в профиле из перечня предложенных на сайте Codebattle
  - Добавить возможность выбора локализации интерфейса
  - Дабавить возможность сменить пароль
